kind: Service
apiVersion: v1
metadata:
  name: bitcoind-mainnet-rpc
spec:
  type: ClusterIP
  selector:
    app: bitcoind-mainnet-rpc
  ports:
  - name: rpc-port  
    port: 8332
---
kind: Service
apiVersion: v1
metadata:
  name: bitcoind-mainnet-p2p
spec:
  type: NodePort
  selector:
    app: bitcoind-mainnet-p2p
  ports:
  - name: p2p-port
    port: 34333
    protocol: UDP
    targetPort: 34333
